baseURL: https://plootra.com/
author: Mehmet Dogan
copyright: Copyright © 2023
paginate: 3
languageCode: en
DefaultContentLanguage: en
enableInlineShortcodes: yes
ignoreErrors: error-remote-getjson
theme: "hugo-paper"
title: Plootra | Analytics for financial markets and investing
# disqusShortname: xxxxx # to enable Disqus in the website
googleAnalytics: G-2MNSX43ZM3
enableEmoji: true

permalinks:
  /: /:year/:month/:slug/
  # post: /:year/:month/:slug/ # originally it was /:year/:month/:title/
  
params:
  # avatar: nanxiaobei@gmail.com
  bio: Discover fresh research
  color: linen  # linen, wheat, gray, light
  github: doganmehmet
  # instagram: n/a
  # name: Mehmet
  # twitter: n/a
  description: Plootra is your guide to analytics for financial markets and investing with R and Python. Both languages are extensively used by invesment professionals in banks, investment funds, and asset management firms.
  rss: true
  graphCommentId: plootra
  showReadingTime: true
  
markup:
  goldmark:
    renderer:
      unsafe: yes
menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 10
    - identifier: shiny
      name: Shiny
      url: /shiny/
      weight: 10

      
taxonomies:
  category: categories
  series: series
  tag: tags
privacy:
  instagram:
    disabled: no
    simple: yes
  twitter:
    disabled: no
    enableDNT: yes
    simple: yes
  vimeo:
    disabled: no
    simple: yes
  youtube:
    disabled: no
    privacyEnhanced: yes
services:
  instagram:
    disableInlineCSS: yes
  twitter:
    disableInlineCSS: yes
